<a href="https://colab.research.google.com/github/ysn-gachon/AI-Class-202335225-nayeonsu/blob/main/Week4/titanic_attempt2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv')

from sklearn.preprocessing import LabelEncoder







le = LabelEncoder()






df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
# 각 컬럼별로 빈 데이터(NaN)가 몇 개인지 출력
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [25]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 가장 빈도가 높은 값(최빈값)으로 채우기
mode_val = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(mode_val)

In [26]:
# Name 컬럼 인코딩

df['Name_encoded'] = le.fit_transform(df['Name'])
df['Sex_encoded'] = le.fit_transform(df['Sex'])
df['Ticket_encoded'] = le.fit_transform(df['Ticket'])
df['Embarked_encoded'] = le.fit_transform(df['Embarked'])

In [27]:
y = df['Survived']
print(y.value_counts())

Survived
0    549
1    342
Name: count, dtype: int64

In [28]:
X = df.drop(['PassengerId', 'Survived', 'Name', 'Ticket', 'Cabin', 'Embarked', 'Sex'], axis=1)


X.head()

,Pclass,Age,SibSp,Parch,Fare,Name_encoded,Sex_encoded,Ticket_encoded,Embarked_encoded
0,3,22.0,1,0,7.2500,108,1,523,2
1,1,38.0,1,0,71.2833,190,0,596,0
2,3,26.0,0,0,7.9250,353,0,669,2
3,1,35.0,1,0,53.1000,272,0,49,2
4,3,35.0,0,0,8.0500,15,1,472,2

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [30]:
X_train

,Pclass,Age,SibSp,Parch,Fare,Name_encoded,Sex_encoded,Ticket_encoded,Embarked_encoded
105,3,28.000000,0,0,7.8958,542,1,354,2
68,3,17.000000,4,2,7.9250,25,0,248,2
253,3,30.000000,1,0,16.1000,487,1,536,2
320,3,22.000000,0,0,7.2500,211,1,524,2
706,2,45.000000,0,0,13.5000,434,0,108,2
...,...,...,...,...,...,...,...,...,...
835,1,39.000000,1,1,83.1583,175,0,609,0
192,3,19.000000,1,0,7.8542,20,0,406,2
629,3,29.699118,0,0,7.7333,602,1,286,1
559,3,36.000000,1,0,17.4000,885,0,300,2
684,2,60.000000,1,1,39.0000,112,1,240,2

In [31]:
X_test

,Pclass,Age,SibSp,Parch,Fare,Name_encoded,Sex_encoded,Ticket_encoded,Embarked_encoded
495,3,29.699118,0,0,14.4583,880,1,176,0
648,3,29.699118,0,0,7.5500,865,1,620,2
278,3,7.000000,4,1,29.1250,681,1,480,1
31,1,29.699118,1,0,146.5208,776,0,586,0
255,3,29.000000,0,2,15.2458,819,0,185,0
...,...,...,...,...,...,...,...,...,...
167,3,45.000000,1,4,27.9000,760,0,337,2
306,1,29.699118,0,0,110.8833,248,0,83,0
379,3,19.000000,0,0,7.7750,314,1,324,2
742,1,21.000000,2,2,262.3750,711,0,602,0
10,3,4.000000,1,1,16.7000,727,0,616,2

In [32]:
y_train

105    0
68     1
253    0
320    0
706    1
      ..
835    1
192    1
629    0
559    1
684    0
Name: Survived, Length: 668, dtype: int64

In [33]:
y_test

495    0
648    0
278    0
31     1
255    1
      ..
167    0
306    1
379    0
742    1
10     1
Name: Survived, Length: 223, dtype: int64

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
0.7802690582959642
[[115  24]
 [ 25  59]]

In [35]:
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.7488789237668162
[[107  32]
 [ 24  60]]

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Random Forest ---
0.852017937219731
[[127  12]
 [ 21  63]]

In [37]:
X_selected = df[['Pclass', 'Sex_encoded', 'Age']]

X_selected.head()

   Pclass  Sex_encoded   Age
0       3            1  22.0
1       1            0  38.0
2       3            0  26.0
3       1            0  35.0
4       3            1  35.0

In [38]:
X_selected_train, X_selected_test, y_train, y_test = train_test_split(X_selected, y,test_size=0.25,random_state=0)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_selected_train, y_train)

pred_lr = clf_lr.predict(X_selected_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
0.7937219730941704
[[117  22]
 [ 24  60]]

In [40]:
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_selected_train, y_train)

pred_dt = clf_dt.predict(X_selected_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.7757847533632287
[[118  21]
 [ 29  55]]

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_selected_train, y_train)
pred = rf_clf.predict(X_selected_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Random Forest ---
0.7982062780269058
[[119  20]
 [ 25  59]]